# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.spatial
import model_utils.fields
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20160628_0925'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, default='')),
                ('location', location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326, verbose_name='location')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=12, verbose_name='phone')),
            ],
            options={
                'ordering': ('routepointm2m__point_number',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, default='')),
                ('center', location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326, verbose_name='center')),
                ('popularity', models.PositiveIntegerField(blank=True, null=True, verbose_name='popularity')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='cost')),
                ('extremality', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='extremality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePointM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='point number')),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='SavedRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Route', verbose_name='route')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tourist', verbose_name='tourist')),
            ],
            options={
                'verbose_name_plural': 'Saved by',
                'verbose_name': 'Saved by',
            },
        ),
        migrations.CreateModel(
            name='AdminPoint',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Point')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.point',),
        ),
        migrations.CreateModel(
            name='CompanyPoint',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Point')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='company')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.point',),
        ),
        migrations.AddField(
            model_name='routepointm2m',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Point', verbose_name='point'),
        ),
        migrations.AddField(
            model_name='routepointm2m',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Route', verbose_name='route'),
        ),
        migrations.AddField(
            model_name='route',
            name='points',
            field=models.ManyToManyField(through='main.RoutePointM2M', to='main.Point', verbose_name='points'),
        ),
        migrations.AddField(
            model_name='route',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_by', through='main.SavedRoutes', to='users.Tourist', verbose_name='saved_by'),
        ),
        migrations.AddField(
            model_name='route',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tourist', verbose_name='tourist'),
        ),
    ]
