# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('inn', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='inn')),
                ('kpp', models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='kpp')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=12, verbose_name='phone')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'verbose_name': 'Company',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.NullBooleanField(choices=[(False, 'female'), (True, 'male')], verbose_name='gender')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age')),
                ('martial_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'married')], null=True, verbose_name='martial status')),
            ],
            options={
                'verbose_name': 'Tourist',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
